Repository boostcampwm-2021/web09-Duxcord, pull requests merged in 2021-11, with the labels that each got.

#18 Feature/redux setting
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/redux/slice.test.ts
  client/src/redux/slice.ts
  client/src/redux/store.ts
Labels: 👷 chore, 🧪 test

#19 Feature/session login
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/controller/user.controller.ts
  server/src/db/index.ts
  server/src/entity/User.ts
  server/src/entity/base.entity.ts
  server/src/entity/session.entity.ts
  server/src/entity/user.entity.ts
  server/src/index.ts
  server/src/router/api.router.ts
  server/src/router/api/user.router.ts
Labels: 🌟 feature, 👷 chore

#21 Chore/cors
  server/package-lock.json
  server/package.json
  server/src/index.ts
Labels: 👷 chore

#25 Style/#22
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/styles/GlobalStyle.tsx
  client/src/styles/colors.tsx
  client/src/styles/fonts/PretendardVariable.woff2
  client/src/types/fonts.d.ts
Labels: 🎨 style

#28 docs: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 👷 chore

#26 react app 빌드 스크립트 추가 close #8
  .github/workflows/check-build-express.yml
  .github/workflows/check-build-react-strict.yml
  .github/workflows/check-build-react.yml
  client/package-lock.json
Labels: 👷 chore

#49 Fix : userController.signUp 회원정보 저장을 기다리지 않고 응답하는 것을 수정
  server/src/controller/user.controller.ts
Labels: 🔪 fix

#51 Fix : 로그인 페이지 스타일링 수정
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignIn/style.tsx
Labels: 🔪 fix, 🎨 style

#52 Style/로그인/회원가입 페이지 배경 레이아웃
  client/public/ducks.jpg
  client/src/layouts/BackgroundLayout/index.tsx
  client/src/layouts/BackgroundLayout/style.tsx
  client/src/pages/SignIn/index.tsx
  client/src/styles/GlobalStyle.tsx
Labels: 🎨 style, 👷 chore

#53 Feat : 로그인 여부에 따라 API 접근을 제한하는 accessControl 미들웨어
  server/src/controller/user.controller.ts
  server/src/router/api/user.router.ts
  server/src/util/index.ts
Labels: 🌟 feature

#54 회원가입 페이지 레이아웃 구현
  client/src/App.tsx
  client/src/pages/SignUp/index.test.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/style.tsx
Labels: 🎨 style, 🧪 test

#55 Feature/get user data
  server/src/controller/user.controller.ts
  server/src/db/index.ts
  server/src/db/repository/user.repository.ts
  server/src/router/api/user.router.ts
Labels: 🌟 feature

#57 Style/#38
  client/public/icons/addChannel.png
  client/public/icons/addGroup.png
  client/public/icons/camOff.png
  client/public/icons/camOn.png
  client/public/icons/channelClose.png
  client/public/icons/channelOpen.png
  client/public/icons/delete.png
  client/public/icons/headerFix.png
  client/public/icons/headerMention.png
  client/public/icons/headerNotification.png
  client/public/icons/headerQuestion.png
  client/public/icons/headerUsers.png
  client/public/icons/inviteGroup.png
  client/public/icons/meetingChannel.png
  client/public/icons/micOff.png
  client/public/icons/micOn.png
  client/public/icons/speakerOff.png
  client/public/icons/speakerOn.png
  client/public/icons/textChannel.png
  client/src/layouts/MainLayout/ChannelHeaderLayout/index.tsx
  client/src/layouts/MainLayout/ChannelHeaderLayout/style.tsx
  client/src/layouts/MainLayout/ChannelListLayout/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/style.tsx
  client/src/layouts/MainLayout/GroupListLayout/index.tsx
  client/src/layouts/MainLayout/GroupListLayout/style.tsx
  client/src/layouts/MainLayout/index.tsx
  client/src/layouts/MainLayout/style.tsx
Labels: 🌟 feature, 🎨 style, 👷 chore

#59 멤버의 그룹들 조회, 그룹의 멤버들 조회하는 API
  server/src/controller/group.controller.ts
  server/src/controller/user.controller.ts
  server/src/router/api/group.router.ts
  server/src/router/api/user.router.ts
Labels: 🌟 feature

#61 회원가입 기능 구현 및 로그인 페이지와 연동
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/style.tsx
  client/src/util/checkResponse.tsx
Labels: 🌟 feature

#56 Chore/test setup
  .gitignore
  server/package-lock.json
  server/package.json
  server/src/controller/user.controller.test.ts
  server/src/controller/user.controller.ts
  server/src/index.ts
  server/tsconfig.json
  server/webpack.config.js
Labels: 👷 chore, 🧪 test

#64 Feature/사용자 장치 상태 추가, interactive style 적용
  client/public/icons/camOn.png
  client/src/layouts/MainLayout/ChannelHeaderLayout/index.test.tsx
  client/src/layouts/MainLayout/ChannelListLayout/index.test.tsx
  client/src/layouts/MainLayout/ChannelListLayout/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/style.tsx
  client/src/layouts/MainLayout/GroupListLayout/style.tsx
Labels: 🌟 feature, 🔪 fix, 🎨 style, 👷 chore, 🧪 test

#63 Feature/signup validation
  server/src/controller/user.controller.ts
Labels: 🌟 feature, ♻️ refactor

#65 로그인 페이지 기능 구현
  client/src/App.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignIn/style.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/style.tsx
  client/src/util/checkResponse.tsx
  client/src/util/fetchOptions.tsx
  client/src/util/fetcher.tsx
Labels: 🌟 feature, 🎨 style

#66 그룹생성 시 디폴트 채널 2개 생성, 유저의 전체 그룹조회 시 채널도 조회 가능
  server/src/controller/group.controller.ts
  server/src/controller/user.controller.ts
  server/src/db/index.ts
  server/src/db/repository/groupmember.repository.ts
  server/src/entity/meetingchannel.entity.ts
  server/src/entity/textchannel.entity.ts
Labels: 🌟 feature

#67 Test/signIn Fix/signUp
  server/src/controller/user.controller.test.ts
  server/src/controller/user.controller.ts
Labels: 🧪 test

#71 Refactor/fonts 폴더 위치 변경
  client/public/fonts/PretendardVariable.woff2
  client/src/styles/GlobalStyle.tsx
Labels: ♻️ refactor

#72 엔티티 이름 바꾸기
  server/src/controller/group.controller.ts
  server/src/db/index.ts
  server/src/entity/groupmember.entity.ts
  server/src/entity/meetingchannel.entity.ts
  server/src/entity/reaction.entity.ts
  server/src/entity/text.entity.ts
  server/src/entity/textchannel.entity.ts
  server/src/entity/user.entity.ts
  server/src/entity/workgroup.entity.ts
Labels: 🔪 fix, 👷 chore

#73 LoginPage / LogoutPage 라우팅 및 인풋 테스트 코드 작성
  client/src/App.test.tsx
  client/src/pages/SignIn/index.test.tsx
  client/src/pages/SignUp/index.test.tsx
Labels: 🧪 test

#69 Refactor/ChannelListLayout에서 컴포넌트 분리
  client/src/layouts/MainLayout/ChannelListLayout/Channel/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/Channel/style.tsx
  client/src/layouts/MainLayout/ChannelListLayout/GroupSetting/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/GroupSetting/style.tsx
  client/src/layouts/MainLayout/ChannelListLayout/Profile/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/Profile/style.tsx
  client/src/layouts/MainLayout/ChannelListLayout/index.test.tsx
  client/src/layouts/MainLayout/ChannelListLayout/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/style.tsx
Labels: ♻️ refactor

#79 Refactor : 프론트엔드 구조 변경
  client/src/App.tsx
  client/src/components/ChannelHeader/index.test.tsx
  client/src/components/ChannelHeader/index.tsx
  client/src/components/ChannelHeader/style.tsx
  client/src/components/SideBar/Channel/index.tsx
  client/src/components/SideBar/Channel/style.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupNav/style.tsx
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/components/SideBar/GroupSetting/style.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/components/SideBar/Profile/style.tsx
  client/src/components/SideBar/index.test.tsx
  client/src/components/SideBar/index.tsx
  client/src/components/SideBar/style.tsx
  client/src/components/common/Background/index.tsx
  client/src/components/common/Background/style.tsx
  client/src/layouts/BackgroundLayout/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/index.tsx
  client/src/layouts/MainLayout/ChannelListLayout/style.tsx
  client/src/layouts/MainLayout/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Main/style.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
Labels: ♻️ refactor

#81 채팅채널에 채팅 생성 API 제작
  server/src/controller/channel.controller.ts
  server/src/db/index.ts
  server/src/router/api.router.ts
  server/src/router/api/channel.router.ts
Labels: 🌟 feature

#82 Feature/group list
  client/src/api/API_URL.ts
  client/src/components/ChannelHeader/index.tsx
  client/src/components/SideBar/Channel/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/Channels/style.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupNav/style.tsx
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/components/SideBar/index.tsx
  client/src/components/common/Background/style.tsx
  client/src/hooks/useGroups.ts
  client/src/hooks/useSelectedGroup.ts
  client/src/redux/selectedChannel/slice.ts
  client/src/redux/selectedGroup/slice.ts
  client/src/redux/slice.test.ts
  client/src/redux/slice.ts
  client/src/redux/store.ts
Labels: 🌟 feature

#83 채팅 목록을 받을 수 있는 API 제작
  server/src/controller/channel.controller.ts
  server/src/db/index.ts
  server/src/db/repository/text.repository.ts
  server/src/router/api/channel.router.ts
Labels: 🌟 feature

#84 채팅 창 퍼블리싱
  client/public/icons/btn-like.svg
  client/public/icons/btn-text-add-file.svg
  client/public/icons/btn-thread.svg
  client/src/components/Chat/AddChatReaction/index.tsx
  client/src/components/Chat/AddChatReaction/style.tsx
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatInput/style.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatItem/style.tsx
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Main/style.tsx
  client/src/types/chats.d.ts
Labels: 🌟 feature, 🎨 style

#96 Feat/ 채팅 채널에 쓰레드 생성 API 만들기
  server/src/controller/text.controller.ts
  server/src/db/index.ts
  server/src/entity/text.entity.ts
  server/src/entity/thread.entity.ts
  server/src/router/api.router.ts
  server/src/router/api/text.router.ts
Labels: 🌟 feature

#92 Feat/ 그룹에 채널 생성 API 만들기
  server/src/controller/group.controller.ts
  server/src/router/api/group.router.ts
Labels: 🌟 feature

#97 Feature/#75chat
  client/package-lock.json
  client/package.json
  client/public/images/default_profile.png
  client/public/images/ducks.jpg
  client/public/images/duxcord_logo.png
  client/src/api/API_URL.ts
  client/src/api/postChat.ts
  client/src/components/ChannelHeader/index.tsx
  client/src/components/ChannelHeader/style.ts
  client/src/components/Chat/AddChatReaction/style.ts
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatInput/style.ts
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.ts
  client/src/components/Chat/style.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/style.ts
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupNav/style.ts
  client/src/components/SideBar/GroupSetting/style.ts
  client/src/components/SideBar/Profile/style.ts
  client/src/components/SideBar/style.ts
  client/src/components/common/Background/style.ts
  client/src/hooks/useGroups.ts
  client/src/hooks/useSelectedChannel.ts
  client/src/hooks/useSelectedGroup.ts
  client/src/pages/Main/index.tsx
  client/src/pages/Main/style.ts
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignIn/style.ts
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/style.ts
  client/src/styles/GlobalStyle.ts
  client/src/styles/colors.ts
  client/src/types/chats.d.ts
  client/src/util/checkResponse.ts
  client/src/util/fetchOptions.ts
  client/src/util/fetcher.ts
  client/src/util/socket.ts
  server/package-lock.json
  server/package.json
  server/src/controller/channel.controller.ts
  server/src/controller/group.controller.ts
  server/src/controller/user.controller.ts
  server/src/db/repository/text.repository.ts
  server/src/index.ts
  server/src/socket.ts
Labels: 🌟 feature, ♻️ refactor

#101 회원가입 실시간 유효성 검사 구현
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/style.ts
  client/src/util/api.ts
  client/src/util/checkResponse.ts
  client/src/util/message.ts
Labels: 🌟 feature

#100 그룹 가입 모달 생성 및 API 연결
  client/public/icons/btn-close-modal.svg
  client/src/api/API_URL.ts
  client/src/api/postChat.ts
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/GroupJoin/style.ts
  client/src/components/Modal/index.tsx
  client/src/components/Modal/style.ts
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/types/modal.d.ts
  server/src/controller/group.controller.ts
Labels: 🌟 feature, 🎨 style

#98 Feat/유저 정보 조회, 수정 API 만들기
  server/src/controller/user.controller.ts
  server/src/router/api/user.router.ts
Labels: 🌟 feature

#103 그룹 오버플로우, 모달 z-index, 모달 텍스트 안지워짐 해결
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/style.ts
  client/src/components/SideBar/GroupNav/style.ts
Labels: 🔪 fix

#107 회원가입 유효성 검사 버그 수정
  client/src/pages/SignUp/index.tsx
Labels: 🔪 fix

#105 Fix : chatListRef.current 가 null 인 경우 return 하도록 수정
  client/src/components/Chat/index.tsx
Labels: 🔪 fix

#109 Chore/cd스크립트
  .github/workflows/check-build-express.yml
  .github/workflows/deploy.yml
  client/public/favicon.ico
  client/public/index.html
  server/webpack.config.js
Labels: 📄 documentation, 👷 chore, 🏷 deploy

#121 Refactor/styles의 Colors enum으로 변경
  client/src/components/ChannelHeader/style.ts
  client/src/components/Chat/AddChatReaction/style.ts
  client/src/components/Chat/ChatInput/style.ts
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/style.ts
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/GroupJoin/style.ts
  client/src/components/Modal/style.ts
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
  client/src/components/SideBar/Channels/style.ts
  client/src/components/SideBar/GroupNav/style.ts
  client/src/components/SideBar/GroupSetting/style.ts
  client/src/components/SideBar/Profile/style.ts
  client/src/components/SideBar/style.ts
  client/src/pages/SignIn/style.ts
  client/src/pages/SignUp/style.ts
  client/src/styles/Colors.ts
  client/src/styles/colors.ts
Labels: ♻️ refactor

#119 Fix : socket room에 채널 타입 prefix 추가
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  server/src/controller/channel.controller.ts
Labels: 🔪 fix

#122 Feat : 로그인 여부에 따라 사용자 접근을 제한하는 RestrictedRoute
  client/src/App.tsx
  client/src/api/API_URL.ts
  client/src/components/common/RestrictedRoute/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
Labels: 🎄frontend

#126 Style/레이아웃 깨지지 않게 변경
  client/src/components/ChannelHeader/style.ts
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/Channels/style.ts
  client/src/components/SideBar/GroupNav/style.ts
  client/src/components/SideBar/GroupSetting/style.ts
  client/src/components/SideBar/Profile/style.ts
  client/src/components/SideBar/index.tsx
  client/src/components/SideBar/style.ts
  client/src/styles/GlobalStyle.ts
Labels: 🔪 fix, 🎨 style

#131 Feature/#124 새로고침시 원래 그룹/채널 복귀
  client/src/api/STATUS_CODES.ts
  client/src/components/Chat/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/common/RestrictedRoute/index.tsx
  client/src/hooks/useAccessControl.ts
  client/src/hooks/useGroups.ts
  client/src/hooks/useUserdata.ts
  client/src/pages/Main/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/util/getURLParams.ts
Labels: 🌟 feature, 🔪 fix, 🎄frontend

#130 좋아요 API 만들기, 채팅 조회 API 응답 수정하기
  server/src/controller/channel.controller.ts
  server/src/controller/chat.controller.ts
  server/src/db/index.ts
  server/src/db/repository/chat.repository.ts
  server/src/router/api/chat.router.ts
Labels: 🌟 feature, 🛠backend

#133 Chore/#123 프론트 prettier 연동!
  client/.eslintrc.json
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/src/api/postChat.ts
  client/src/components/Chat/AddChatReaction/index.tsx
  client/src/components/Chat/AddChatReaction/style.ts
  client/src/components/Chat/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/index.tsx
  client/src/components/SideBar/style.ts
  client/src/index.tsx
  client/src/pages/Main/style.ts
  client/src/pages/SignIn/style.ts
  client/src/pages/SignUp/style.ts
  client/src/styles/Colors.ts
  client/src/util/api.ts
  client/src/util/checkResponse.ts
  client/src/util/fetchOptions.ts
  client/src/util/fetcher.ts
  client/src/util/message.ts
Labels: 👷 chore

#132 Feat/WebRTC API로 화상 채팅 구현 - 개인 화면 출력
  client/src/components/Meet/MeetButton/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
  client/src/components/Meet/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/hooks/useUserDevice.ts
  client/src/pages/Main/index.tsx
  client/src/redux/store.ts
  client/src/redux/userDevice/slice.ts
Labels: 🌟 feature

#137 Fix/#123
  client/src/components/ChannelHeader/style.ts
  client/src/components/Meet/MeetButton/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
  client/src/components/SideBar/GroupSetting/style.ts
  client/src/components/SideBar/Profile/index.tsx
  client/src/redux/store.ts
  client/src/redux/userDevice/slice.ts
Labels: 🔪 fix

#139 Fix#134 #138
  client/package-lock.json
  client/package.json
  client/src/pages/SignIn/index.tsx
  client/src/setupProxy.js
Labels: 🐞 bug, 👷 chore

#142 Feat/WebRTC 연결
  client/src/components/Meet/MeetVideo/index.tsx
  server/src/socket.ts
Labels: 🆘 help wanted, 🌟 feature

#140 Refactor : 소켓 joinChannel, leaveChannel emit 코드 분리
  client/src/components/Chat/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/pages/Main/index.tsx
  client/src/util/socket.ts
Labels: ♻️ refactor, 🎄frontend

#141 그룹 추가 => 그룹 생성 / 참가 로 연결하는 모달을 만들고 API 붙이기
  client/public/icons/btn-image-add.svg
  client/public/icons/btn-image-upload.svg
  client/src/api/API_URL.ts
  client/src/api/postChat.ts
  client/src/api/postCreateGroup.ts
  client/src/api/postJoinGroup.ts
  client/src/components/Modal/GroupAdd/index.tsx
  client/src/components/Modal/GroupAdd/style.ts
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupCreate/style.ts
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Modal/style.ts
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/types/modal.d.ts
  server/src/controller/group.controller.ts
Labels: 🌟 feature, 🎄frontend

#143 현재 유저 접속 인원 보여주는 기능 구현
  client/src/components/Chat/UserConnection/UserConnection.tsx
  client/src/components/Chat/UserConnection/style.ts
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.ts
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/hooks/useGroupConnection.ts
  client/src/hooks/useGroups.ts
  client/src/redux/groupConnection/slice.ts
  client/src/redux/store.ts
  client/src/styles/Colors.ts
  server/src/db/repository/groupmember.repository.ts
  server/src/socket.ts
Labels: 🌟 feature

#144 좋아요 기능 구현
  client/src/api/API_URL.ts
  client/src/api/STATUS_CODES.ts
  client/src/api/postLikeChat.ts
  client/src/components/Chat/AddChatReaction/index.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatReaction/index.tsx
  client/src/components/Chat/ChatReaction/style.ts
  client/src/components/Chat/index.tsx
  client/src/types/chats.d.ts
  server/src/controller/chat.controller.ts
Labels: 🌟 feature

#145 Feature : meeting채널 화상 회의 기능 구현
  client/src/components/Meet/MeetVideo/index.tsx
  server/src/socket.ts
Labels: 🐞 bug, 🌟 feature, 🎄frontend, 🛠backend

#153 자기가 좋아요 누른건 색깔 다르게
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatReaction/index.tsx
  client/src/components/Chat/ChatReaction/style.ts
  client/src/styles/Colors.ts
  client/src/types/chats.d.ts
Labels: 🌟 feature, 🎄frontend

#152 쓰레드 컴포넌트 만들기
  client/public/icons/threadClose.png
  client/src/components/Chat/AddChatReaction/index.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/Thread/style.ts
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.ts
  client/src/hooks/useSelectedChat.ts
  client/src/redux/selectedChat/slice.ts
  client/src/redux/store.ts
Labels: 🌟 feature

#154 Feat/화상회의 레이아웃 잡기
  client/src/components/Meet/MeetButton/index.tsx
  client/src/components/Meet/MeetButton/style.ts
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
  client/src/components/Meet/index.tsx
  client/src/components/Meet/style.ts
Labels: 🎨 style

#155 Refactor/meet 캠/마이크 온오프 채널 입장 즉시 적용되지 않던 문제 수정 및 하드코딩... 처치
  client/src/components/Meet/MeetVideo/index.tsx
  client/tsconfig.json
Labels: 🔪 fix, ♻️ refactor

#151 그룹 초대 모달 생성
  client/src/components/Modal/GroupInvite/index.tsx
  client/src/components/Modal/GroupInvite/style.ts
  client/src/components/Modal/style.ts
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/components/SideBar/GroupSetting/style.ts
Labels: 🎄frontend

#159 쓰레드 조회 API 만들기, 쓰레드 생성 API 수정, 채팅 조회 API 수정
  server/src/controller/chat.controller.ts
  server/src/db/index.ts
  server/src/db/repository/chat.repository.ts
  server/src/db/repository/thread.repository.ts
  server/src/entity/chat.entity.ts
  server/src/router/api/chat.router.ts
Labels: 🌟 feature, 🔪 fix, 🛠backend

#161 쓰레드를 받아와 현재 화면에 보여준다.
  client/src/api/API_URL.ts
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/Thread/style.ts
  client/src/components/Chat/ThreadItem/index.tsx
  client/src/components/Chat/ThreadItem/style.ts
  client/src/components/Chat/ThreadPreview/index.tsx
  client/src/components/Chat/ThreadPreview/style.ts
  client/src/types/chats.d.ts
  client/src/types/threads.d.ts
  client/src/util/fetcher.ts
Labels: 🌟 feature, 🎨 style, 🎄frontend

#162 Feature/meetchat 화상채널 내 채팅 기능! 및 화상채널 내 비디오 뮤트
  client/public/icons/btn-close-meetchat.svg
  client/public/icons/btn-show-meetchat.svg
  client/src/components/Meet/MeetButton/style.ts
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetChat/style.ts
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/index.tsx
  client/src/components/Meet/style.ts
  server/src/socket.ts
Labels: 🌟 feature, 🎨 style, 🎄frontend

#163 Feat/화상회의 중인 사용자 목록 조회
  client/src/components/SideBar/Channels/MeetingUserList/index.tsx
  client/src/components/SideBar/Channels/MeetingUserList/style.ts
  client/src/components/SideBar/Channels/index.tsx
  server/src/socket.ts
Labels: 🌟 feature

#166 Patch : 소켓을 이용한 ThreadChat 실시간 갱신
  client/src/components/Chat/Thread/index.tsx
  client/src/setupProxy.js
  server/src/controller/chat.controller.ts
Labels: 🔪 fix

#165 쓰레드 인풋 API 연결, 소켓 연결
  client/src/api/API_URL.ts
  client/src/api/postCreateThread.ts
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/index.tsx
  server/src/controller/channel.controller.ts
  server/src/controller/chat.controller.ts
Labels: 🎄frontend

#172 Feat/화상 레이아웃 수정 - 사용자 이름 출력, border-radius 주기
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
Labels: 🌟 feature

#170 Feat/좌측바 하단에 로그인한 사용자 표시
  client/src/components/SideBar/Profile/index.tsx
  client/src/components/SideBar/Profile/style.ts
Labels: 🌟 feature

#175 [Feat/#169] 접속인원 파악 로직 수정 / 로그아웃 버튼 생성
  client/src/components/ChannelHeader/index.tsx
  client/src/components/ChannelHeader/style.ts
  client/src/components/SideBar/GroupNav/index.tsx
Labels: 🔪 fix, 🎨 style

#176 feat: 모달 열고 닫을 때 애니메이션 추가
  client/src/components/Modal/index.tsx
  client/src/components/Modal/style.ts
Labels: 🌟 feature, 🎨 style, 🎄frontend

#178 bug: stream이 없는 경우에도 socket 작동하도록 변경
  client/src/components/Meet/MeetVideo/index.tsx
Labels: 🐞 bug, 🔪 fix

#180 Patch/sprint3 useAccessControl 수정, 콘솔 로그 제거, 리스트 아이템 key 누락 수정 등
  client/src/components/Chat/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/SideBar/Channels/MeetingUserList/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/hooks/useAccessControl.ts
Labels: 🔪 fix

#183 fix : myStream 다시 체크하도록 롤백
  client/src/components/Meet/MeetVideo/index.tsx
Labels: 🐞 bug

#193 Fix : getMyStream 함수에서 getUserMedia로 스트림 생성에 실패했을 때 더미 스트림 생성
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/pages/Main/index.tsx
Labels: 🔪 fix, 🎄frontend

#192 Refactor : useAccessControl 개선
  client/src/hooks/useAccessControl.ts
Labels: ♻️ refactor, 🎄frontend

#197 ()=>{}을 ()=>void 타입으로 통합, 통일성 있게 prop 넘기기
  client/src/components/Chat/AddChatReaction/index.tsx
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatReaction/index.tsx
  client/src/components/Chat/ThreadPreview/index.tsx
  client/src/components/Modal/GroupAdd/index.tsx
Labels: ♻️ refactor, 🎄frontend

#202 Refactor/모듈 절대경로로 불러오도록 설정
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ChannelHeader/index.tsx
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/ThreadItem/index.tsx
  client/src/components/Chat/ThreadPreview/index.tsx
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Chat/index.tsx
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Modal/GroupAdd/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupInvite/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/Logout/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/components/common/RestrictedRoute/index.tsx
  client/src/customTypes/chats.d.ts
  client/src/customTypes/fonts.d.ts
  client/src/customTypes/modal.d.ts
  client/src/customTypes/threads.d.ts
  client/src/hooks/useGroupConnection.ts
  client/src/hooks/useGroups.ts
  client/src/hooks/useSelectedChannel.ts
  client/src/hooks/useSelectedChat.ts
  client/src/hooks/useSelectedGroup.ts
  client/src/hooks/useUserDevice.ts
  client/src/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
  client/tsconfig.json
  client/tsconfig.paths.json
Labels: ♻️ refactor

#205 fix: 모달 이전 버튼이 제대로 작동하지 않는 오류 해결
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Modal/style.ts
Labels: 🎨 style, 🎄frontend

#204 Refactor/하드코딩 제거!(API_URL과 소켓이벤트 관련)
  client/src/api/API_URL.ts
  client/src/api/URL.ts
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Chat/index.tsx
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/Logout/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/customTypes/socket/ChannelEvent.ts
  client/src/customTypes/socket/ChatEvent.ts
  client/src/customTypes/socket/GroupEvent.ts
  client/src/customTypes/socket/LikeEvent.ts
  client/src/customTypes/socket/MeetEvent.ts
  client/src/customTypes/socket/ThreadEvent.ts
  client/src/hooks/useAccessControl.ts
  client/src/hooks/useGroups.ts
  client/src/pages/SignIn/index.tsx
  client/src/util/api.ts
  client/src/util/socket.ts
  package-lock.json
Labels: 🔪 fix, ♻️ refactor, 🎄frontend

#200 Refactor/change architecture 백엔드 폴더구조 변경!!!
  server/src/controllers/channel.controller.ts
  server/src/controllers/chat.controller.ts
  server/src/controllers/group.controller.ts
  server/src/controllers/socket/meeting.socket.ts
  server/src/controllers/user.controller.test.ts
  server/src/controllers/user.controller.ts
  server/src/db/entities/base.entity.ts
  server/src/db/entities/chat.entity.ts
  server/src/db/entities/chattingchannel.entity.ts
  server/src/db/entities/file.entity.ts
  server/src/db/entities/groupmember.entity.ts
  server/src/db/entities/index.ts
  server/src/db/entities/meetingchannel.entity.ts
  server/src/db/entities/reaction.entity.ts
  server/src/db/entities/session.entity.ts
  server/src/db/entities/thread.entity.ts
  server/src/db/entities/user.entity.ts
  server/src/db/entities/workgroup.entity.ts
  server/src/db/repositories/chat.repository.ts
  server/src/db/repositories/groupmember.repository.ts
  server/src/db/repositories/index.ts
  server/src/db/repositories/thread.repository.ts
  server/src/db/repositories/user.repository.ts
  server/src/index.ts
  server/src/loaders/app.loader.ts
  server/src/loaders/orm.loader.ts
  server/src/loaders/socket.loader.ts
  server/src/routes/api.router.ts
  server/src/routes/api/channel.router.ts
  server/src/routes/api/chat.router.ts
  server/src/routes/api/group.router.ts
  server/src/routes/api/user.router.ts
  server/src/utils/access-control.middleware.ts
  server/src/utils/index.ts
Labels: 🔪 fix, 👷 chore, ♻️ refactor, 🛠backend

#198 Refactor : hooks 폴더에 index.ts 추가해 하나의 파일에서 커스텀 훅들을 import 할 수 있도록 개선
  client/src/components/ChannelHeader/index.tsx
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Chat/index.tsx
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupInvite/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/components/SideBar/index.tsx
  client/src/components/common/RestrictedRoute/index.tsx
  client/src/hooks/index.ts
  client/src/pages/Main/index.tsx
  client/src/setupTests.ts
  client/src/types/chats.d.ts
  client/src/types/fonts.d.ts
  client/src/types/modal.d.ts
  client/src/types/socket/ChannelEvent.ts
  client/src/types/socket/ChatEvent.ts
  client/src/types/socket/GroupEvent.ts
  client/src/types/socket/LikeEvent.ts
  client/src/types/socket/MeetEvent.ts
  client/src/types/socket/ThreadEvent.ts
  client/src/types/threads.d.ts
  client/tsconfig.paths.json
  server/src/loaders/orm.loader.ts
Labels: ♻️ refactor, 🎄frontend

#223 chore : dev 브랜치 배포 서버 세팅 및 dev 브랜치 배포 스크립트
  .github/workflows/deploy-dev.yml
Labels: 👷 chore

#226 백엔드 코드에서 하드코딩된 코드들 enum, 상수 사용하도록 수정
  server/src/controllers/channel.controller.ts
  server/src/controllers/chat.controller.ts
  server/src/controllers/group.controller.ts
  server/src/controllers/user.controller.ts
  server/src/loaders/socket.loader.ts
  server/src/types/ChannelType.ts
  server/src/types/socket/ChannelEvent.ts
  server/src/types/socket/ChatEvent.ts
  server/src/types/socket/ConnectionEvent.ts
  server/src/types/socket/GroupEvent.ts
  server/src/types/socket/LikeEvent.ts
  server/src/types/socket/MeetEvent.ts
  server/src/types/socket/RoomPrefix.ts
  server/src/types/socket/ThreadEvent.ts
Labels: ♻️ refactor, 🛠backend

#222 Fix/브라우저에 스크롤이 생기는 것 없애기
  client/src/components/Chat/ChatInput/style.ts
  client/src/components/Chat/UserConnection/style.ts
  client/src/styles/GlobalStyle.ts
Labels: 🔪 fix

#228 Fix : dev 배포 스크립트 PORT => PORT_DEV로 변경
  .github/workflows/deploy-dev.yml
Labels: 👷 chore

#224 채널 추가 모달과 API 연결
  client/src/api/API_URL.ts
  client/src/api/postCreateChannel.ts
  client/src/components/Modal/ChannelCreate/ChannelTypeItem/index.tsx
  client/src/components/Modal/ChannelCreate/ChannelTypeItem/style.ts
  client/src/components/Modal/ChannelCreate/index.tsx
  client/src/components/Modal/ChannelCreate/style.ts
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/common/Icon/asset/ic-circle-deselected.svg
  client/src/components/common/Icon/asset/ic-circle-selected.svg
  client/src/components/common/Icon/index.ts
  server/src/controllers/group.controller.ts
Labels: 🌟 feature, 🎨 style, 🎄frontend

#227 [Feat/#219] 현재 말하고 있는 사용자 테두리 하이라이팅 구현
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
  client/src/util/audio.ts
Labels: 🌟 feature, 🎄frontend

#233 chat, meetChat 컴포넌트 스크롤 UX 개선
  client/src/components/Chat/index.tsx
  client/src/components/Meet/MeetChat/index.tsx
Labels: 🔪 fix, 🎄frontend

#229 feat: 선택된 채널의 색깔을 진하게 바꾸기
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
Labels: 🎨 style, 🎄frontend

#230 Feat/그룹 삭제
  client/src/api/API_URL.ts
  client/src/api/deleteGroup.ts
  client/src/components/Modal/GroupDelete/index.tsx
  client/src/components/Modal/GroupDelete/style.ts
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/styles/Colors.ts
  client/src/types/socket/GroupEvent.ts
  client/src/util/fetchOptions.ts
  server/src/controllers/group.controller.ts
  server/src/db/repositories/group.repository.ts
  server/src/db/repositories/groupmember.repository.ts
  server/src/db/repositories/index.ts
  server/src/loaders/orm.loader.ts
  server/src/loaders/socket.loader.ts
  server/src/routes/api/group.router.ts
  server/src/types/socket/GroupEvent.ts
Labels: 🌟 feature

#237 [Feat/#234] 자신의 마이크를 쓰거나 캠을 끄면 썸네일을 대신 보여주는 기능 구현(마이크는 마이크off 아이콘)
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
  client/src/components/SideBar/Profile/index.tsx
  client/src/types/socket/MeetEvent.ts
  server/src/controllers/socket/meet.socket.ts
  server/src/loaders/socket.loader.ts
  server/src/types/socket/MeetEvent.ts
Labels: 🌟 feature

#238 사진 업로드 기능 추가
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/api/postCreateGroup.ts
  client/src/assets/icons/ic-group-thumbnail-upload.svg
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupCreate/style.ts
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupNav/style.ts
  client/src/components/common/Icons/index.ts
  client/src/utils/fetchOptions.ts
  client/src/utils/uploadFile.ts
Labels: 🌟 feature, 🎄frontend

#240 Fix : 리렌더링시 stream이 바뀌지 않아도 VideoItem이 깜빡이던 문제 수정
  client/src/components/Meet/MeetVideo/index.tsx
Labels: 🔪 fix

#243 Refactor : OtherVideo 컴포넌트 분리, OtherVideo 개선
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
Labels: 🔪 fix, ♻️ refactor

#245 Style/채팅, 스레드 레이아웃 변경
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/Thread/style.ts
  client/src/components/Chat/style.ts
Labels: 🎨 style

#248 [Feat/#247] 화상회의 인원 제한 기능 / 화상 인원 목록 버그 수정
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/MeetingUserList/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/types/socket/MeetEvent.ts
  server/src/controllers/socket/meet.socket.ts
  server/src/types/socket/MeetEvent.ts
Labels: 🌟 feature

#249 [Fix/#191] 화상회의 채널에서 브라우저를 닫아 퇴장하는 경우 회의 멤버 목록에서 제거되지 않는 버그 제거
  server/src/controllers/socket/group.socket.ts
  server/src/controllers/socket/meet.socket.ts
  server/src/types/socket/ConnectionEvent.ts
Labels: 🔪 fix

#255 Chore : 배포 스크립트에 client 빌드전 환경변수 파일 생성 스크립트 추가
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy.yml
Labels: 👷 chore

#253 [Feat/#252] 스피커 음소거 기능 구현
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/types/socket/MeetEvent.ts
  server/src/controllers/socket/meet.socket.ts
  server/src/loaders/socket.loader.ts
  server/src/types/socket/MeetEvent.ts
Labels: 🌟 feature

#250 사용자 정보 조회 모달 만들기
  client/src/api/API_URL.ts
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Modal/UserInformation/index.tsx
  client/src/components/Modal/UserInformation/style.ts
  client/src/components/SideBar/Profile/index.tsx
  client/src/hooks/index.ts
  client/src/hooks/useOtherUserdata.ts
  client/src/hooks/useSelectedUser.ts
  client/src/redux/selectedUser/slice.ts
  client/src/redux/store.ts
  client/src/types/modal.d.ts
  server/src/controllers/user.controller.ts
Labels: 🌟 feature, 🎄frontend

#256 [Fix/#246] 유저 목록 갱신 시 복수개의 윈도우를 띄운 유저가 한 윈도우를 닫으면 Offline으로 보이는 오류 수정
  server/src/controllers/socket/group.socket.ts
  server/src/controllers/socket/meet.socket.ts
Labels: 🔪 fix

#257 Feat/채널 선택 전 빈 화면에 이미지 추가
  client/src/components/common/Empty/index.tsx
  client/src/components/common/Empty/style.ts
  client/src/pages/Main/index.tsx
  client/src/styles/GlobalStyle.ts
Labels: 🌟 feature, 🎨 style

#251 Feat/채팅 작성 시 이미지 업로드
  client/src/api/postChat.ts
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatInput/style.ts
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/Thread/style.ts
  client/src/components/Chat/ThreadPreview/style.ts
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Chat/UserConnection/style.ts
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.ts
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetChat/style.ts
  client/src/pages/Main/style.ts
  client/src/styles/Colors.ts
  client/src/types/chats.d.ts
  client/src/utils/fetchOptions.ts
  server/src/controllers/channel.controller.ts
  server/src/db/repositories/chat.repository.ts
  server/src/loaders/orm.loader.ts
Labels: 🌟 feature, 🎨 style, 🎄frontend, 🛠backend

#261 [Fix/#258] 한 명의 사용가 여러개의 브라우저로 화상채널에 들어오면 화면끄기와 음소거 등이 잘 작동하지 않는 오류 제거
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/SideBar/Channels/MeetingUserList/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  server/src/controllers/socket/meet.socket.ts
Labels: 🔪 fix

#263 Fix : url변경시 history push대신 replace 사용하도록 수정
  client/src/components/Modal/ChannelCreate/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupDelete/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/Logout/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/hooks/useAccessControl.ts
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
Labels: 🔪 fix, 🎄frontend

#259 Feat/화면 공유 기능
  client/src/components/Meet/MeetVideo/MeetButton/index.tsx
  client/src/components/Meet/MeetVideo/MeetButton/style.ts
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/index.tsx
  client/src/utils/audio.ts
Labels: 🌟 feature, 🔪 fix, ♻️ refactor, 🎄frontend

#264 style: 그룹 목록 애니메이션 적용
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupNav/style.ts
Labels: 🆘 help wanted, 🎨 style

#265 프로필 수정 모달 구현
  client/src/api/API_URL.ts
  client/src/api/patchUserdata.ts
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Modal/UserEdit/index.tsx
  client/src/components/Modal/UserEdit/style.ts
  client/src/components/Modal/UserInformation/index.tsx
  client/src/types/modal.d.ts
  client/src/utils/fetchOptions.ts
Labels: 🌟 feature, 🎄frontend

#269 hotfix : 화상 회의 채널 채팅을 열었을 때 스크롤이 바로 최하단으로 가지 않고 부드럽게 내려가던 것을 수정
  client/src/components/Meet/MeetChat/index.tsx
Labels: 🔪 fix, 🎄frontend

#270 프로필 조회 모달을 어디서나 띄울 수 있게 함
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Modal/style.ts
  client/src/components/SideBar/Profile/index.tsx
  client/src/components/SideBar/Profile/style.ts
Labels: 🎨 style, 🎄frontend

#272 🚑 유저 정보 중 안 보이거나 스타일이 넘치는 경우 수정
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Modal/UserEdit/style.ts
  client/src/components/Modal/UserInformation/style.ts
  client/src/components/SideBar/Profile/style.ts
Labels: 🎨 style

#273 Hotfix : 화상 회의 채널 캠 오프시 프로필 이미지가 원본사이즈로 표시되는 문제 수정
  client/src/components/Meet/MeetChat/style.ts
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
Labels: 🔪 fix, 🎨 style

#274 4주차 Hotfix
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Chat/UserConnection/style.ts
  client/src/components/Meet/MeetChat/style.ts
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
  client/src/components/Modal/UserEdit/style.ts
  client/src/components/Modal/UserInformation/style.ts
  client/src/components/SideBar/Profile/style.ts
Labels: 🔪 fix, 🏷 deploy

#277 refactor: 임포트 시 alias가 제대로 먹지 않은 부분 수정, 임포트 순서 변경
  client/src/components/ChannelHeader/index.tsx
  client/src/components/Chat/AddChatReaction/index.tsx
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatReaction/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/ThreadItem/index.tsx
  client/src/components/Chat/ThreadPreview/index.tsx
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Chat/index.tsx
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetVideo/MeetButton/index.tsx
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/index.tsx
  client/src/components/Modal/ChannelCreate/ChannelTypeItem/index.tsx
  client/src/components/Modal/ChannelCreate/index.tsx
  client/src/components/Modal/GroupAdd/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupDelete/index.tsx
  client/src/components/Modal/GroupInvite/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/Logout/index.tsx
  client/src/components/Modal/UserEdit/index.tsx
  client/src/components/Modal/UserInformation/index.tsx
  client/src/components/Modal/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/components/SideBar/index.tsx
  client/src/components/common/Background/index.tsx
  client/src/components/common/Empty/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
Labels: ♻️ refactor

#280 [Feat/#279] 채팅을 날짜별로 묶어서 보여주는 기능 구현
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.ts
  client/src/utils/makeChatSection.ts
Labels: 🌟 feature, 🎄frontend

#283 Feat/통화 종료 버튼 구현
  client/src/assets/icons/ic-meeting-stop.svg
  client/src/assets/icons/ic-screen-share-start.svg
  client/src/assets/icons/ic-screen-share-stop.svg
  client/src/components/Meet/MeetVideo/MeetButton/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
Labels: 🌟 feature

#285 [Feat/#281] 세션스토리지에 현재 사용자 화상상태를 저장해 새로고침해도 적용되도록 구현
  client/src/redux/userDevice/slice.ts
  client/src/utils/storage.ts
Labels: 🌟 feature, 🎄frontend

#288 chore : Group 인터페이스 추가
  client/package-lock.json
  client/src/components/Modal/ChannelCreate/index.tsx
  client/src/components/Modal/GroupDelete/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupNav/style.ts
  client/src/hooks/useGroups.ts
  client/src/pages/Main/index.tsx
  client/src/types/group.ts
Labels: 👷 chore, 🎄frontend

#289 style: 화상 채팅에서 내가 보낸 채팅은 오른쪽 정렬하도록 스타일 변경
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetChat/style.ts
Labels: 🎨 style

#292 Style/오른쪽 사이드바 너비 변경, 유저목록 hover, 화상 회의 사용자 목록 썸네일 출력 외 2
  client/src/assets/icons/ic-channel-chatting.svg
  client/src/components/Chat/ChatInput/style.ts
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/Thread/style.ts
  client/src/components/Chat/UserConnection/style.ts
  client/src/components/Chat/style.ts
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
  client/src/components/SideBar/Channels/MeetingUserList/index.tsx
  client/src/components/SideBar/Channels/MeetingUserList/style.ts
  client/src/components/SideBar/Channels/style.ts
  client/src/components/SideBar/GroupSetting/index.tsx
  client/src/components/SideBar/GroupSetting/style.ts
Labels: 🔪 fix, 🎨 style

#294 fix: 쓰레드에 이미지가 출력되도록 수정, 채팅 글씨 크기 조정 및 초단위 표시 제거
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/Thread/style.ts
  client/src/components/Chat/ThreadItem/index.tsx
  client/src/components/Chat/ThreadItem/style.ts
  client/src/components/Chat/ThreadPreview/index.tsx
  client/src/components/Chat/ThreadPreview/style.ts
Labels: 🔪 fix

#295 Feat/#286
  client/src/api/API_URL.ts
  client/src/api/deleteChannel.ts
  client/src/components/Modal/ChannelDelete/index.tsx
  client/src/components/Modal/ChannelDelete/style.ts
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/types/socket/GroupEvent.ts
  server/src/controllers/group.controller.ts
  server/src/loaders/socket.loader.ts
  server/src/routes/api/group.router.ts
  server/src/types/socket/GroupEvent.ts
Labels: 🌟 feature, 🎄frontend, 🛠backend

#296 [Fix/#290] 채팅을 스크롤할 때 새로불러운 chat이 있을 때 스크롤이 정상적인 위치에 오지 않는 오류 수정
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/index.tsx
  client/src/utils/functionalProgramming.ts
  client/src/utils/getChatsHeight.ts
Labels: 🔪 fix, 🎄frontend

#297 Fix/오른쪽 사이드바 유저 목록과 쓰레드 너비 다르게 구현
  client/src/components/Chat/ChatItem/style.ts
  client/src/components/Chat/Thread/style.ts
  client/src/components/Chat/ThreadPreview/style.ts
  client/src/components/Chat/index.tsx
  client/src/components/Chat/style.ts
  client/src/components/SideBar/Channels/MeetingUserList/style.ts
Labels: 🔪 fix

#301 Feat : 화상 회의 채널에서 안읽은 채팅 메시지 알림
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetChat/style.ts
Labels: 🌟 feature, 🔪 fix, 🎄frontend

#299 Feat : 화상 회의 채널에서 비디오 클릭시 크게 보기
  client/src/components/Meet/MeetVideo/FocusedVideo/index.tsx
  client/src/components/Meet/MeetVideo/FocusedVideo/style.ts
  client/src/components/Meet/MeetVideo/MeetButton/style.ts
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Meet/MeetVideo/style.ts
  client/src/components/Meet/index.tsx
  client/src/components/Meet/style.ts
  client/src/hooks/index.ts
  client/src/hooks/useSelectVideo.ts
Labels: 🌟 feature, 🎨 style, 🎄frontend

#305 Fix : MeetChat의 input이 MeetButtonWrapper에 가려져서 클릭하지 못하는 문제 수정
  client/src/components/Meet/MeetVideo/MeetButton/style.ts
  client/src/components/Meet/MeetVideo/style.ts
Labels: 🔪 fix

#307 [Refactor/functionalProgramming] 기존의 getChatHegith 함수 리팩토링
  client/src/components/Chat/index.tsx
  client/src/utils/functionalProgramming.ts
  client/src/utils/getChatsHeight.ts
Labels: ♻️ refactor

#308 베이스 토스트 만들기
  client/src/App.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/common/Toast/Item/index.tsx
  client/src/components/common/Toast/Item/style.ts
  client/src/components/common/Toast/index.tsx
  client/src/components/common/Toast/style.ts
  client/src/hooks/index.ts
  client/src/hooks/useToast.ts
  client/src/redux/store.ts
  client/src/redux/toast/slice.ts
  client/src/types/toast.d.ts
Labels: 🌟 feature, 🎨 style, 🎄frontend

#310 곳곳에 토스트 굽기
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Modal/ChannelCreate/index.tsx
  client/src/components/Modal/ChannelCreate/style.ts
  client/src/components/Modal/ChannelDelete/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupCreate/style.ts
  client/src/components/Modal/GroupDelete/index.tsx
  client/src/components/Modal/GroupInvite/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/Logout/index.tsx
  client/src/components/Modal/UserEdit/index.tsx
  client/src/components/Modal/UserEdit/style.ts
  client/src/components/common/Toast/Item/style.ts
  client/src/utils/message.ts
Labels: 🌟 feature, 🎄frontend

#315 Fix : 불필요한 모듈 가져오기 제거, 채널리스트 아이템의 아이콘 z-index 수정
  client/src/components/Meet/style.ts
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
Labels: 🔪 fix, 🎨 style, 🎄frontend

#314 Fix : ontrack 이벤트 핸들러에서 cam과 screen 스트림을 streamID로 구분하도록 수정
  client/src/components/Meet/MeetVideo/index.tsx
  server/src/controllers/socket/meet.socket.ts
Labels: 🔪 fix, 🎄frontend, 🛠backend

#319 [Fix/InfinityScroll] 무한 스크롤 로직 수정
  client/src/utils/functionalProgramming.ts
  client/src/utils/getChatsHeight.ts
Labels: ♻️ refactor

#325 우측 상단 안 쓰는 아이콘 제거
  client/src/assets/icons/ic-header-alert.svg
  client/src/assets/icons/ic-header-fix.svg
  client/src/assets/icons/ic-header-mention.svg
  client/src/assets/icons/ic-header-question.svg
  client/src/assets/icons/ic-header-users.svg
  client/src/components/ChannelHeader/index.tsx
  client/src/components/common/Icons/index.ts
Labels: 🎨 style, 👷 chore

#320 Fix/S3 백엔드로 이동, pre-signed url로 업로드 기능 구현
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy.yml
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/api/API_URL.ts
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/UserEdit/index.tsx
  client/src/utils/getPresignedUrl.ts
  client/src/utils/uploadFile.ts
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/controllers/user.controller.ts
  server/src/routes/api/user.router.ts
  server/src/utils/S3.ts
Labels: 🔪 fix, 🎄frontend, 🛠backend

#322 Style/선택된 그룹 표시
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/GroupNav/style.ts
Labels: 🎨 style

#327 Chore : server 웹팩 설정에 S3 환경변수 추가
  server/webpack.config.js
Labels: 👷 chore

#326 Feat : 화상회의 채널 입/퇴장 효과음 추가
  client/public/sounds/meet_join.wav
  client/public/sounds/meet_leave.wav
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/hooks/index.ts
  client/src/hooks/useSoundEffect.ts
Labels: 🎄frontend

#328 Fix : 웹팩 config S3.REGION => S3_REGION 오타 수정
  server/webpack.config.js
Labels: 🔪 fix, 👷 chore

#333 빌드 스크립트 수정
  .github/workflows/check-build-express.yml
Labels: 👷 chore, 🛠backend

#329 Fix : useSoundEffect를 playSoundEffect 유틸 함수로 변경
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/hooks/index.ts
  client/src/utils/playSoundEffect.ts
Labels: 🔪 fix, ♻️ refactor, 🎄frontend

#330 MeetVideo 컴포넌트 리팩토링 및 새로고침시 연결이 안되는 버그 수정, 로딩 스크린 추가, 프론트 소켓 연결 개선
  client/src/App.tsx
  client/src/components/Meet/MeetVideo/FocusedVideo/index.tsx
  client/src/components/Meet/MeetVideo/MeetButton/style.ts
  client/src/components/Meet/MeetVideo/MyVideo/index.tsx
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/common/Empty/index.tsx
  client/src/hooks/index.ts
  client/src/hooks/useSelectVideo.ts
  client/src/hooks/useSocket.ts
  client/src/pages/Loading/index.tsx
  client/src/pages/Loading/style.ts
  client/src/pages/Main/index.tsx
  client/src/types/meet.ts
  client/src/types/socket/InitEvent.ts
  client/src/utils/socket.ts
  server/src/controllers/socket/meet.socket.ts
  server/src/loaders/socket.loader.ts
  server/src/types/socket/InitEvent.ts
Labels: 🔪 fix, ♻️ refactor, 🎄frontend

#331 인생 네컷 화면 캡쳐 기능 구현
  client/package-lock.json
  client/package.json
  client/src/assets/icons/ic-capture.svg
  client/src/components/Meet/MeetVideo/MeetButton/index.tsx
  client/src/components/Meet/MeetVideo/MeetButton/style.ts
  client/src/components/Meet/MeetVideo/MyVideo/index.tsx
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/common/Icons/index.ts
  client/src/styles/GlobalStyle.ts
  client/src/types/socket/MeetEvent.ts
  client/src/utils/browserChecker.ts
  client/src/utils/capture.ts
  client/src/utils/message.ts
Labels: 🌟 feature, 🎄frontend

#332 [Feat/#318] 화상회의 접속인원 표시 기능 구현
  client/src/components/SideBar/Channels/ChannelListItem/ChannelMeetingCount/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/ChannelMeetingCount/style.ts
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/style.ts
Labels: 🌟 feature, 🎄frontend

#337 Refactor/client 내부 api, utils 절대경로로 변경
  client/package-lock.json
  client/src/api/deleteChannel.ts
  client/src/api/deleteGroup.ts
  client/src/api/patchUserdata.ts
  client/src/api/postChat.ts
  client/src/api/postCreateChannel.ts
  client/src/api/postCreateGroup.ts
  client/src/api/postCreateThread.ts
  client/src/api/postJoinGroup.ts
  client/src/api/postLikeChat.ts
  client/src/api/postLogout.ts
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/ChatItem/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/components/Chat/UserConnection/index.tsx
  client/src/components/Chat/index.tsx
  client/src/components/Meet/MeetChat/index.tsx
  client/src/components/Meet/MeetVideo/MeetButton/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/Modal/ChannelCreate/index.tsx
  client/src/components/Modal/ChannelDelete/index.tsx
  client/src/components/Modal/GroupCreate/index.tsx
  client/src/components/Modal/GroupDelete/index.tsx
  client/src/components/Modal/GroupInvite/index.tsx
  client/src/components/Modal/GroupJoin/index.tsx
  client/src/components/Modal/Logout/index.tsx
  client/src/components/Modal/UserEdit/index.tsx
  client/src/components/SideBar/Channels/ChannelListItem/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/GroupNav/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/hooks/useAccessControl.ts
  client/src/hooks/useGroups.ts
  client/src/hooks/useOtherUserdata.ts
  client/src/hooks/useSocket.ts
  client/src/hooks/useUserdata.ts
  client/src/pages/Main/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
  client/src/redux/userDevice/slice.ts
  client/src/utils/api.ts
  client/src/utils/getPresignedUrl.ts
  client/tsconfig.paths.json
Labels: ♻️ refactor

#336 Fix : 메인페이지 접속시 서버로부터 그룹리스트 가져오기가 완료된 후 렌더링 되도록 수정
  client/src/hooks/useGroups.ts
  client/src/pages/Main/index.tsx
Labels: 🔪 fix, 🎄frontend

#334 Fix : 다음 페이지 요청중일 때는 스크롤이 끝에 도달해도 더 요청하지 않도록 수정
  client/src/components/Chat/index.tsx
Labels: 🔪 fix, 🎄frontend

#339 Fix/비밀번호 유효성 검사 변경
  client/src/utils/checkResponse.ts
  client/src/utils/message.ts
  server/src/controllers/user.controller.ts
Labels: 🔪 fix

#342 Fix : MeetVideo 컴포넌트의 RTC 관련 useEffect의 의존성 배열에 userdata 추가
  client/src/components/Meet/MeetVideo/index.tsx
Labels: 🔪 fix, 🎄frontend
