Repository boostcampwm-2021/web09-Duxcord, pull requests merged in 2021-12, with the labels that each got.

#372 Refactor : MeetVideo 컴포넌트 리팩토링
  client/src/components/Meet/MeetVideo/FocusedVideo/index.tsx
  client/src/components/Meet/MeetVideo/MyVideo/index.tsx
  client/src/components/Meet/MeetVideo/OtherVideo/index.tsx
  client/src/components/Meet/MeetVideo/index.tsx
  client/src/components/SideBar/Channels/index.tsx
  client/src/components/SideBar/Profile/index.tsx
  client/src/hooks/index.ts
  client/src/hooks/useAccessControl.ts
  client/src/hooks/useChatInfinite.ts
  client/src/hooks/useChatSocket.ts
  client/src/hooks/useChats.ts
  client/src/hooks/useControlMyStrem.ts
  client/src/hooks/useCreatePeerConnection.ts
  client/src/hooks/useGroups.ts
  client/src/hooks/useMeeting.ts
  client/src/hooks/useOtherUserdata.ts
  client/src/hooks/useScreenShare.ts
  client/src/hooks/useSelectVideo.ts
  client/src/hooks/useSocket.ts
  client/src/hooks/useToast.ts
  client/src/hooks/useUpdateMembersDeviceState.ts
  client/src/hooks/useUserdata.ts
  client/src/types/meet.d.ts
  client/src/utils/constants/SOCKET_EVENT.ts
  client/src/utils/index.ts
  client/src/utils/socket.ts
  client/src/utils/stream.ts
  server/src/controllers/socket/meet.socket.ts
  server/src/loaders/socket.loader.ts
  server/src/types/socket/MeetEvent.ts
Labels: 🔪 fix, ♻️ refactor, 🎄frontend

#374 Feat : CustomError와 CatchError 데코레이터 추가와 그에 따른 에러 핸들링 미들웨어 수정
  server/src/controllers/channel.controller.ts
  server/src/controllers/chat.controller.ts
  server/src/controllers/group.controller.ts
  server/src/controllers/user.controller.test.ts
  server/src/controllers/user.controller.ts
  server/src/loaders/express.loader.ts
  server/src/messages/channel.mesage.ts
  server/src/messages/chat.message.ts
  server/src/messages/user.message.ts
  server/src/routes/api/channel.router.ts
  server/src/routes/api/chat.router.ts
  server/src/routes/api/group.router.ts
  server/src/routes/api/user.router.ts
  server/src/utils/CatchError.ts
  server/src/utils/validators/channel.validator.ts
  server/src/utils/validators/chat.validator.ts
  server/src/utils/validators/group.validator.ts
  server/src/utils/validators/user.validator.ts
Labels: 🌟 feature, 🛠backend

#375 [Test/front util] api 테스트 작성
  client/src/utils/test/api.test.ts
Labels: 🧪 test

#378 [Test/ft] localStorage test 및 기타 util함수 테스트
  client/package-lock.json
  client/package.json
  client/src/utils/makeChatSection.ts
  client/src/utils/test/makeChatSection.test.ts
  client/src/utils/test/storage.test.ts
Labels: 🧪 test

#379 Fix : 소켓 setDeviceState 이벤트 자기 자신에게는 broadcast 되지 않도록 수정
  server/src/controllers/socket/meet.socket.ts
Labels: 🔪 fix, 🛠backend

#380 refactor: Chat 컴포넌트 계층적으로 폴더 구조 변경
  client/src/components/Chat/ChatList/ChatItem/AddChatReaction/index.tsx
  client/src/components/Chat/ChatList/ChatItem/AddChatReaction/style.ts
  client/src/components/Chat/ChatList/ChatItem/ChatReaction/index.tsx
  client/src/components/Chat/ChatList/ChatItem/ChatReaction/style.ts
  client/src/components/Chat/ChatList/ChatItem/ThreadPreview/index.tsx
  client/src/components/Chat/ChatList/ChatItem/ThreadPreview/style.ts
  client/src/components/Chat/ChatList/ChatItem/index.tsx
  client/src/components/Chat/ChatList/ChatItem/style.ts
  client/src/components/Chat/ChatList/index.tsx
  client/src/components/Chat/ChatList/style.ts
  client/src/components/Chat/style.ts
Labels: ♻️ refactor, 🎄frontend

#382 핫픽스!
  client/src/components/Modal/GroupDelete/index.tsx
  client/src/components/Modal/Logout/index.tsx
  client/src/hooks/useMeeting.ts
  client/src/utils/stream.ts
Labels: 🔪 fix

#383 Hotfix : 핫픽스2!
  client/src/components/SideBar/GroupNav/index.tsx
  server/src/controllers/socket/meet.socket.ts
Labels: 🔪 fix, 🎄frontend

#384 Fix : 채팅 메시지, 스레드 댓글 추가를 http 요청 대신 소켓 사용하도록 변경
  client/src/components/Chat/ChatInput/index.tsx
  client/src/components/Chat/Thread/index.tsx
  client/src/hooks/useSocket.ts
  client/src/pages/SignIn/index.tsx
  client/src/utils/constants/SOCKET_EVENT.ts
  server/src/controllers/socket/chat.socket.ts
  server/src/loaders/express.loader.ts
  server/src/loaders/root.loader.ts
  server/src/loaders/socket.loader.ts
  server/src/types/socket/ChatEvent.ts
Labels: 🔪 fix

#387 Fix : 다른사람의 메시지를 수신하고 있을 때 인피니트 스크롤이 동작하지 않는 문제 수정
  client/src/hooks/useChatInfinite.ts
Labels: 🔪 fix, 🎄frontend

#390 Fix : 기존 멤버와 WebRTC 연결시 오퍼가 2번 등록되는 문제 수정
  client/src/hooks/useMeeting.ts
  server/src/controllers/socket/chat.socket.ts
  server/src/controllers/socket/meet.socket.ts
  server/src/loaders/socket.loader.ts
Labels: 🔪 fix, 🎄frontend, 🛠backend

#391 Fix : 기존 멤버와 WebRTC 연결시 오퍼가 2번 등록되는 문제 수정
  client/src/hooks/useMeeting.ts
  server/src/controllers/socket/meet.socket.ts
Labels: 🔪 fix, 🎄frontend, 🛠backend
